### ISSUE TITLE
zmq_ctx_new: implementation not found?

### ISSUE THREAD

**Issue by joelburton** [rmculpepper/racket-zeromq#1]
I am trying to use your package to use iracket, but cannot. It's unclear if this is a bug in the software or in my configuration [the docs for this library don't specify required versions of libzmq]

Setup:
- zmq [tried 2.2.0, 3.2.5, and 4.2.5, all from MacPorts]
- MacOSX 10.13.6 [High Sierra]
- Racket 7.0

When I run the tests for this library ("raco test -p zeromq-r"), I get the following [repeated several times, followed by hanging]

```
zmq_ctx_new: implementation not found; no arguments provided
  context...:
   /Users/joel/Library/Racket/7.0/pkgs/zeromq-r-lib/main.rkt:124:0
   /Applications/Racket v7.0/collects/racket/contract/private/arrow-val-first.rkt:428:3
   /Users/joel/Library/Racket/7.0/pkgs/zeromq-r/tests/hello.rkt:24:0: hello-client
```

Is there a required version of libzmq? With zmq 4.2.5, I have "libzmq.5.dylib" [softlinked to "libzmq.dylib"], which seems, on my reading, to be what this lib's `private/ffi.rkt` is looking for.

It appears the auto buildbot for Racket's pkg-build is also failing: https://pkg-build.racket-lang.org/server/built/test-fail/zeromq-r.txt

Thanks for any pointers.

**Comment by joelburton** [comment]
Changing line 18 of `~/Library/Racket/7.0/pkgs/zeromq-r-lib/private/ffi.rkt` to 

```racket
(ffi-lib "/opt/local/lib/libzmq" '(#f "5") #:fail (lambda () #f))
```

Seems to fix the problem. Is this a problem with my configuration? Or would most people need to put in a path to their libzmq?

**Comment by rmculpepper** [comment]
I haven't tried MacPorts, but a google search suggests that they install libraries to `/opt/local/lib`, and maybe that's not in the OS default library search path? Homebrew installs them to `/usr/local/lib` (via symlinks, anyway), and that works for me (on an older version of Mac OS).

You might try linking `libzmq.5.dylib` into one of the directories shown by 

    racket -e "(require setup/dirs)(get-lib-search-dirs)"

Maybe MacPorts has some information about `/opt/local` and search paths?

**Comment by joelburton** [comment]
Interesting, `(get-lib-search-dirs)` only shows Racket's lib dirs, and doesn't show *any* system dirs (including `/opt/local/lib`). I'll dig into that, though. Thanks for the suggestion & for the product. (I did get IRacket working and will be using it to demo Racket in a Python-oriented class, so thanks!)

A suggestion in `~/Library/Racket/7.0/pkgs/zeromq-r-lib/private/ffi.rkt`, might it make sense to change:

```racket
    (ffi-lib "libzmq" '(#f "5") #:fail (lambda () #f))
```

to 

```racket
    (ffi-lib "libzmq" '(#f "5") #:fail (lambda () (error "Can't find libzmq"))
```

Would it ever make sense for this to continue if it can't load libzmq? Part of the challenge I had was that the `make-not-available` stuff masked the real error, and I went down a rabbit hole into `zmq_ctx_new`, when it was really the absence of the total library causing the problem.

**Comment by rmculpepper** [comment]
I think the directories in `(get-lib-search-dirs)` are just searched before the system search path.

In general I think a well-behaved library should never raise an error when it is required. For example, it might be required in an application that only actually uses it in some configurations. (I've run into this problem in the past. The `net/sendmail` library used to raise an error if it couldn't find a sendmail program. I found it very irritating when a script that I didn't want to send mail failed to run because it wasn't able to send mail.)

On the other hand, I think you're right, it would be helpful to tell the user earlier about the missing library. Two thoughts:
- It could log a warning when it was required. This might be confusing or distracting if the program doesn't end up trying to use zeromq, but at least it won't block it from running.
- It could print a warning as part of a post-install hook, so it would be shown when the user installs the package and again whenever they run `raco setup`.
